package com.github.app.api.dao.domain;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer roleId;

    private Role role;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.is_enable
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Short isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.address
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.photo_url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String photoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.remark
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_id
     *
     * @return the value of account.account_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_id
     *
     * @param accountId the value for account.account_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role_id
     *
     * @return the value of account.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role_id
     *
     * @param roleId the value for account.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account
     *
     * @return the value of account.account
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account
     *
     * @param account the value for account.account
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile
     *
     * @return the value of account.mobile
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile
     *
     * @param mobile the value for account.mobile
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.is_enable
     *
     * @return the value of account.is_enable
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Short getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.is_enable
     *
     * @param isEnable the value for account.is_enable
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setIsEnable(Short isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.address
     *
     * @return the value of account.address
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.address
     *
     * @param address the value for account.address
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.photo_url
     *
     * @return the value of account.photo_url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.photo_url
     *
     * @param photoUrl the value for account.photo_url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.remark
     *
     * @return the value of account.remark
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.remark
     *
     * @param remark the value for account.remark
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Account.Builder builder() {
        return new Account.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Account obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Account();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.account_id
         *
         * @param accountId the value for account.account_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder accountId(Integer accountId) {
            obj.setAccountId(accountId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.role_id
         *
         * @param roleId the value for account.role_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder roleId(Integer roleId) {
            obj.setRoleId(roleId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.account
         *
         * @param account the value for account.account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder account(String account) {
            obj.setAccount(account);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.password
         *
         * @param password the value for account.password
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder password(String password) {
            obj.setPassword(password);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.name
         *
         * @param name the value for account.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.sex
         *
         * @param sex the value for account.sex
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder sex(String sex) {
            obj.setSex(sex);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.email
         *
         * @param email the value for account.email
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder email(String email) {
            obj.setEmail(email);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.mobile
         *
         * @param mobile the value for account.mobile
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mobile(String mobile) {
            obj.setMobile(mobile);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.is_enable
         *
         * @param isEnable the value for account.is_enable
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isEnable(Short isEnable) {
            obj.setIsEnable(isEnable);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.address
         *
         * @param address the value for account.address
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder address(String address) {
            obj.setAddress(address);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.photo_url
         *
         * @param photoUrl the value for account.photo_url
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder photoUrl(String photoUrl) {
            obj.setPhotoUrl(photoUrl);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column account.remark
         *
         * @param remark the value for account.remark
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Account build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        accountId("account_id"),
        roleId("role_id"),
        account("account"),
        password("password"),
        name("name"),
        sex("sex"),
        email("email"),
        mobile("mobile"),
        isEnable("is_enable"),
        address("address"),
        photoUrl("photo_url"),
        remark("remark");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}