package com.github.app.api.dao.domain;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.code
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.op_account
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private String opAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.op_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private String opName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.role_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.role_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.description
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_id
     *
     * @return the value of log.log_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_id
     *
     * @param logId the value for log.log_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.code
     *
     * @return the value of log.code
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.code
     *
     * @param code the value for log.code
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.op_account
     *
     * @return the value of log.op_account
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public String getOpAccount() {
        return opAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.op_account
     *
     * @param opAccount the value for log.op_account
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setOpAccount(String opAccount) {
        this.opAccount = opAccount == null ? null : opAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.op_name
     *
     * @return the value of log.op_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.op_name
     *
     * @param opName the value for log.op_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setOpName(String opName) {
        this.opName = opName == null ? null : opName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.role_id
     *
     * @return the value of log.role_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.role_id
     *
     * @param roleId the value for log.role_id
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.role_name
     *
     * @return the value of log.role_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.role_name
     *
     * @param roleName the value for log.role_name
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.description
     *
     * @return the value of log.description
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.description
     *
     * @param description the value for log.description
     *
     * @mbg.generated Thu Feb 08 12:54:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Log.Builder builder() {
        return new Log.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Log obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Log();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.log_id
         *
         * @param logId the value for log.log_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder logId(Long logId) {
            obj.setLogId(logId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.code
         *
         * @param code the value for log.code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder code(String code) {
            obj.setCode(code);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.op_account
         *
         * @param opAccount the value for log.op_account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder opAccount(String opAccount) {
            obj.setOpAccount(opAccount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.op_name
         *
         * @param opName the value for log.op_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder opName(String opName) {
            obj.setOpName(opName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.role_id
         *
         * @param roleId the value for log.role_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder roleId(Integer roleId) {
            obj.setRoleId(roleId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.role_name
         *
         * @param roleName the value for log.role_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder roleName(String roleName) {
            obj.setRoleName(roleName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column log.description
         *
         * @param description the value for log.description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder description(String description) {
            obj.setDescription(description);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Log build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        logId("log_id"),
        code("code"),
        opAccount("op_account"),
        opName("op_name"),
        roleId("role_id"),
        roleName("role_name"),
        description("description");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table log
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}