package com.github.app.api.dao.domain;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.method
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.show_order
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer showOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.is_drop_down
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer isDropDown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.is_show
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.method
     *
     * @return the value of menu.method
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.method
     *
     * @param method the value for menu.method
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setMethod(Integer method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.show_order
     *
     * @return the value of menu.show_order
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.show_order
     *
     * @param showOrder the value for menu.show_order
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.is_drop_down
     *
     * @return the value of menu.is_drop_down
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getIsDropDown() {
        return isDropDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.is_drop_down
     *
     * @param isDropDown the value for menu.is_drop_down
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setIsDropDown(Integer isDropDown) {
        this.isDropDown = isDropDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.is_show
     *
     * @return the value of menu.is_show
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.is_show
     *
     * @param isShow the value for menu.is_show
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Menu.Builder builder() {
        return new Menu.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Menu obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Menu();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.menu_id
         *
         * @param menuId the value for menu.menu_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder menuId(Integer menuId) {
            obj.setMenuId(menuId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.url
         *
         * @param url the value for menu.url
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder url(String url) {
            obj.setUrl(url);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.method
         *
         * @param method the value for menu.method
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder method(Integer method) {
            obj.setMethod(method);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.name
         *
         * @param name the value for menu.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.parent_id
         *
         * @param parentId the value for menu.parent_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder parentId(Integer parentId) {
            obj.setParentId(parentId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.show_order
         *
         * @param showOrder the value for menu.show_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder showOrder(Integer showOrder) {
            obj.setShowOrder(showOrder);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.icon
         *
         * @param icon the value for menu.icon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder icon(String icon) {
            obj.setIcon(icon);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.is_drop_down
         *
         * @param isDropDown the value for menu.is_drop_down
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isDropDown(Integer isDropDown) {
            obj.setIsDropDown(isDropDown);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column menu.is_show
         *
         * @param isShow the value for menu.is_show
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isShow(Integer isShow) {
            obj.setIsShow(isShow);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Menu build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        menuId("menu_id"),
        url("url"),
        method("method"),
        name("name"),
        parentId("parent_id"),
        showOrder("show_order"),
        icon("icon"),
        isDropDown("is_drop_down"),
        isShow("is_show");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table menu
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}