package com.github.app.api.dao.domain;

public class Popedom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popedom.popedom_id
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    private Integer popedomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popedom.name
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popedom.code
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    private String code;

    private String remark;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popedom.popedom_id
     *
     * @return the value of popedom.popedom_id
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public Integer getPopedomId() {
        return popedomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popedom.popedom_id
     *
     * @param popedomId the value for popedom.popedom_id
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public void setPopedomId(Integer popedomId) {
        this.popedomId = popedomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popedom.name
     *
     * @return the value of popedom.name
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popedom.name
     *
     * @param name the value for popedom.name
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popedom.code
     *
     * @return the value of popedom.code
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popedom.code
     *
     * @param code the value for popedom.code
     *
     * @mbg.generated Sat Feb 10 17:18:23 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getRemark() {
        return remark;
    }

    public Popedom setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Popedom.Builder builder() {
        return new Popedom.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Popedom obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Popedom();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column popedom.popedom_id
         *
         * @param popedomId the value for popedom.popedom_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder popedomId(Integer popedomId) {
            obj.setPopedomId(popedomId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column popedom.name
         *
         * @param name the value for popedom.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column popedom.code
         *
         * @param code the value for popedom.code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder code(String code) {
            obj.setCode(code);
            return this;
        }

        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Popedom build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        popedomId("popedom_id"),
        name("name"),
        code("code"),
        remark("remark");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}