package com.github.app.api.dao.domain;

public class RolePopedom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_popedom.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_popedom.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_popedom.role_id
     *
     * @return the value of role_popedom.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_popedom.role_id
     *
     * @param roleId the value for role_popedom.role_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_popedom.menu_id
     *
     * @return the value of role_popedom.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_popedom.menu_id
     *
     * @param menuId the value for role_popedom.menu_id
     *
     * @mbg.generated Tue Jan 30 10:50:05 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static RolePopedom.Builder builder() {
        return new RolePopedom.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role_popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private RolePopedom obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new RolePopedom();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column role_popedom.role_id
         *
         * @param roleId the value for role_popedom.role_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder roleId(Integer roleId) {
            obj.setRoleId(roleId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column role_popedom.menu_id
         *
         * @param menuId the value for role_popedom.menu_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder menuId(Integer menuId) {
            obj.setMenuId(menuId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public RolePopedom build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table role_popedom
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        roleId("role_id"),
        menuId("menu_id");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table role_popedom
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}