package com.github.app.api.dao.mapper;

import com.github.app.api.dao.domain.Popedom;
import com.github.app.api.dao.domain.PopedomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PopedomMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	long countByExample(PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int deleteByExample(PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int deleteByPrimaryKey(Integer popedomId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int insert(Popedom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int insertSelective(Popedom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	List<Popedom> selectByExample(PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	Popedom selectByPrimaryKey(Integer popedomId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Popedom record, @Param("example") PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int updateByExample(@Param("record") Popedom record, @Param("example") PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int updateByPrimaryKeySelective(Popedom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated Sat Feb 10 17:18:23 CST 2018
	 */
	int updateByPrimaryKey(Popedom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	Popedom selectOneByExample(PopedomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsert(@Param("list") List<Popedom> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table popedom
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsertSelective(@Param("list") List<Popedom> list, @Param("selective") Popedom.Column... selective);

	List<Popedom> findPopedomByRoleId(Integer roleId);

	/**
	 * 查询Vue前端界面中用到的权限集合
	 * 
	 * @param roleId
	 * @return
	 */
	List<Popedom> findVuePopedomByRoleId(Integer roleId);

    /**
     * 查询后端服务接口的权限集合
     *
     * @param roleId
     * @return
     */
    List<Popedom> findApiPopedomByRoleId(Integer roleId);

	void truncate();
}